global_frame: map
robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 5.0

footprint: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]
footprint_padding: 0.01

map_type: costmap
static_map: true

plugins: 
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: state_layer, type: "potbot_nav::StateLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

obstacle_layer:
  observation_sources: lrf
  lrf: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}
  
state_layer:
  observation_sources: lrf
  lrf: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}